# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20180213_2230'),
        ('customprofile', '0003_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='keep_menu',
            field=models.ManyToManyField(blank=True, related_name='keep_profile', to='menus.Menu'),
        ),
    ]
