# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0002_auto_20180207_1927'),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userfeed', to='customprofile.UserProfile'),
            preserve_default=False,
        ),
    ]
