# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_storefeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeed',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='profile',
        ),
        migrations.DeleteModel(
            name='UserFeed',
        ),
    ]
