# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shopkeeper',
            field=models.BooleanField(default=False),
        ),
    ]
