# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_auth', '0002_user_is_shopkeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
