# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 12:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='grade',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='hit',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
