# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20180209_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
