# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 13:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20180213_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
