# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('customprofile', '0002_auto_20180207_1927'),
        ('comments', '0001_initial'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='like',
            field=models.ManyToManyField(related_name='review_comment_like', to='customprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comment_profile', to='customprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comment', to='menus.Review'),
        ),
        migrations.AddField(
            model_name='noticecomment',
            name='like',
            field=models.ManyToManyField(related_name='notice_comment_like', to='customprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='noticecomment',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_comment', to='stores.Notice'),
        ),
        migrations.AddField(
            model_name='noticecomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_comment_profile', to='customprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='menucomment',
            name='like',
            field=models.ManyToManyField(related_name='menu_comment_like', to='customprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='menucomment',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_comment', to='menus.Menu'),
        ),
        migrations.AddField(
            model_name='menucomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_comment_profile', to='customprofile.UserProfile'),
        ),
    ]
