# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180207_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucomment',
            old_name='like',
            new_name='like_user',
        ),
        migrations.RenameField(
            model_name='noticecomment',
            old_name='like',
            new_name='like_user',
        ),
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='like',
            new_name='like_user',
        ),
    ]
