# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180209_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucomment',
            name='like_user',
        ),
        migrations.RemoveField(
            model_name='noticecomment',
            name='like_user',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='like_user',
        ),
    ]
