# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hit',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
